blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/denny/adk-agui-middleware/blob/main/README.md
    about: Check the documentation for guides and API reference
  - name: Discussions
    url: https://github.com/denny/adk-agui-middleware/discussions
    about: Ask questions and discuss with the community