name: Question
description: Ask a question about usage, configuration, or best practices
title: "[Question]: "
labels: ["question", "ai-review"]
body:
  - type: markdown
    attributes:
      value: |
        Ask your question here!
        AI will help analyze and provide guidance on your question.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation/Setup
        - Configuration
        - Usage/How-to
        - Best Practices
        - Troubleshooting
        - API/Integration
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about what you're trying to achieve
      placeholder: I'm trying to...
    validations:
      required: true

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already attempted?
      placeholder: I tried...

  - type: textarea
    id: code
    attributes:
      label: Relevant Code
      description: If applicable, provide code snippets
      render: python

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other information that might be helpful