name: Security Vulnerability
description: Report a security vulnerability (please use private disclosure if critical)
title: "[Security]: "
labels: ["security", "ai-review"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT: For critical vulnerabilities, please use GitHub's private vulnerability reporting**

        This issue will be automatically analyzed by AI for security assessment.

  - type: dropdown
    id: severity
    attributes:
      label: Severity (Your Assessment)
      description: How severe do you think this vulnerability is?
      options:
        - Critical - Immediate exploitation possible
        - High - Serious security risk
        - Medium - Moderate security concern
        - Low - Minor security issue
        - Info - Security best practice suggestion
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: There is a potential security issue with...
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      options:
        - SQL Injection
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Authentication Bypass
        - Authorization Issue
        - Sensitive Data Exposure
        - Security Misconfiguration
        - Insecure Dependencies
        - Denial of Service (DoS)
        - Code Injection
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: An attacker could...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: |
        1. Configure...
        2. Send request...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: poc
    attributes:
      label: Proof of Concept
      description: Provide a proof of concept (redact sensitive info)
      render: python

  - type: textarea
    id: affected
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      placeholder: All versions, or specific versions...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: If you have suggestions on how to fix this, please share
      placeholder: This could be fixed by...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant CVEs, CWEs, or references
      placeholder: |
        - CWE-XXX
        - CVE-XXXX-XXXXX
        - https://...