name: AI Issue Assessment

on:
  issues:
    types: [opened, edited, labeled, reopened]
  issue_comment:
    types: [created]

permissions:
  issues: write
  contents: read

jobs:
  ai-assessment:
    if: |
      (github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'edited' || github.event.action == 'reopened' || github.event.label.name == 'ai-review')) ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/ai-review'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Comprehensive AI Assessment
        uses: github/ai-assessment-comment-labeler@v1.0.1
        id: assessment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_number: ${{ github.event.issue.number }}
          issue_body: ${{ github.event.issue.body }}
          ai_review_label: 'ai-review'
          prompts_directory: './.github/prompts'
          labels_to_prompts_mapping: 'bug,bug-assessment.prompt.yml;enhancement,feature-assessment.prompt.yml;question,question-assessment.prompt.yml;security,security-assessment.prompt.yml;all,comprehensive-assessment.prompt.yml;all,duplicate-detection.prompt.yml;all,team-assignment.prompt.yml'
