name: Quick Check

on:
  push:
    branches: [ "**" ]  # Trigger on all branches
  pull_request:
    branches: [ "**" ]

jobs:
  quick-check:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev --frozen

    - name: Quick lint check
      run: |
        uv run ruff check src/ --output-format=github
      continue-on-error: false

    - name: Quick format check
      run: |
        uv run ruff format --check src/
      continue-on-error: false

    - name: Run core tests only
      run: |
        # Only run the most stable core tests for quick feedback
        uv run pytest tests/test_data_model_session.py tests/test_tools_json_encoder.py tests/test_tools_function_name.py -v --tb=short
      continue-on-error: false

    - name: Basic import test
      run: |
        # Test that the main package can be imported
        uv run python -c "import adk_agui_middleware; print('✅ Package imports successfully')"
      continue-on-error: false

  summary:
    runs-on: ubuntu-latest
    needs: quick-check
    if: always()
    steps:
    - name: Check result
      run: |
        if [ "${{ needs.quick-check.result }}" == "success" ]; then
          echo "✅ Quick checks passed! Code is ready for detailed CI."
        else
          echo "❌ Quick checks failed. Please fix issues before pushing."
          exit 1
        fi