name: Security and Quality Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security scan weekly on Monday at 8:00 AM UTC
    - cron: '0 8 * * 1'

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev --frozen

    - name: Run bandit security scan
      run: |
        uv run python -m pip install bandit[toml]
        uv run bandit -r src/ -f json -o bandit-report.json
      continue-on-error: true

    - name: Run safety vulnerability scan
      run: |
        uv run python -m pip install safety
        uv run safety check --json --output safety-report.json
      continue-on-error: true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json
      if: always()

  complexity:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync --dev --frozen

    - name: Run complexity analysis
      run: |
        uv run python -m pip install radon
        uv run radon cc src/ --min C --show-complexity --total-average
        uv run radon mi src/ --min B --show

    - name: Check documentation coverage
      run: |
        uv run python -m pip install interrogate
        uv run interrogate src/ --ignore-init-method --ignore-magic --ignore-nested-functions --fail-under 80 -v
      continue-on-error: true